### ISSUE TITLE
Getting only top 10 most recent tells

### ISSUE THREAD

**Issue by sawzedong** [Logxn/tellonym-python#3]
### Issue
Currently, when I run `client.get_tells()`, the code can only retrieve that most recent 10 tells. 
While I understand that this may be due to the Tellonym API, is there any way to retrieve all tells (or even just not so recent tells)? 

### Recreating issue
By running 
`allTells = client.get_tells()`
`print(allTells)`
Even after adding more tells, the number of items in `allTells` remain at 10. I have also checked that the less recent tells get pushed off.

### Possible Solution?
Wondering if maybe the headers sent could influence this, or maybe some other changes to the link.

Greatly appreciate any help. Thanks.

**Comment by Logxn** [comment]
@sawzedong 

Hello,
sorry for getting back to you so late.

# Fix to this issue
Tellonym has a request parameter called `limit`.
By default this is set to `16`. (Previously set to 10, then 13, now 16)
This limit can be modified perfectly.

I will look trough the Wrapper and will include this in the next update.
I was thinking about ```client.get_tells(int limit)``` would solve this problem.

**Comment by Logxn** [comment]
Should be fixed with this commit 7d31556b45e2a2c4af3f973824c47d6fee554818
If this issue persists, dont hesitate to open a new issue (and maybe tag me so I really get the notification this time haha)
