### ISSUE TITLE
Getting 403 status

### ISSUE THREAD

**Issue by ciprinicu** [Logxn/tellonym-python#5]
title says it all, i tried starting it up and it doesnt work, printed the response from __get_request_token and the response is a 403 (Forbidden)

**Comment by ciprinicu** [comment]
I also forgot to say that I tested a fetch request on a browser and it returned the token just fine, I also saw that you need to use the email and not the username

**Comment by Logxn** [comment]
The json body "email" referes to either the users username OR email.
API should be fixed by now tho
